### PR TITLE
Add channel handle for async messaging

### PR DESCRIPTION
**Pull request by archer884**
I don't believe this is ready to be merged, but feedback might be useful at this stage.

### CODE REVIEW

**Comment by sbstp** [comment]
We can make a trait called IrcSend. The `raw` method must be implemented, but the privmsg, join, etc. are provided. We then implement the trait for Irc and the deferred handle.

edit: This allows us to have code reuse, basically.

**Comment by sbstp** [comment]
I originally gave Irc as a borrow because I wanted to make guarantees about the data it contains, but you don't need the Irc borrow to send data.

**Comment by archer884** [comment]
Cool, I think I see what you're getting at. I'll take a whack at that.

**Comment by sbstp** [comment]
You can probably copy the current implementation of the commands/methods and leave raw undefined. The `ChannelHandle` might have to redefine more methods since the default impl doesn't know about the channel field.

**Comment by sbstp** [comment]
I made a draft of the idea in a branch, [here](https://github.com/sbstp/hiirc/commit/e48c43720de27a8cb56f83b55be66f84a7590c39). Let me know what you think. The peekaboo example does what you want I believe.

**Comment by archer884** [comment]
Cool, I appreciate it. I've been on call at work but will carve out some
time this afternoon if at all possible.

**Comment by sbstp** [comment]
I'm thinking of adding a snapshot feature on `Irc`. You can clone/save the state without having to keep the borrow around. The async result can then act on what the data was when the event occurred, but it's probably not always what you want. Some people probably would like to use the most up to date data. Also cloning the state when there's thousands of users in the channels might be very bad for performance.

**Comment by archer884** [comment]
Yeah, I imagine that's not something you'd want to do under normal circumstances. I can't think of a use case for that off hand, either, although I'm sure someone could come up with one... Like, say you wanted to record some kind of infraction or error completely, but you have concerns that writing the log will take awhile?

With regard to the performance concerns, maybe you could have an option to create the clone using something that also allows users to select a channel or a set of channels (up to and including all of them?) so that you wouldn't necessarily need to clone the state of _all_ channels?

It's _possible_ that if you provide, separately, the ability to clone the a channel or channels (that's where the users, etc., are all stored right? --I don't actually remember off the top of my head), and the functionality you already provide with `.deferred()`, then that would cover the kind of behavior people would want from being able to clone the entire `Irc` object.

(Unless of course I have forgotten something else stored by the object--which is totally possible.)

**Comment by sbstp** [comment]
I've been thinking a lot about this, and I would recommend using coroutines on your end. I'm going to make the Irc object `Send + Sync` so that it can be moved around and cloned easily. The internal state Channel/Users will be easy to access in a thread safe manner. Will probably use a RwLock.

**Comment by archer884** [comment]
Not sure what you mean by coroutines, but I'm certainly open to
suggestions.

**Pull request closed without merging**
